---
title: "desition tree"
author: "Shira, Moria, Naama"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
library(googledrive)
library(glmnetUtils)
library(corrplot)
library(randomForest)
library("devtools")
library("factoextra")
library(ggplot2)
library(rpart)
library(e1071)
library(randomForest)
library(caret)
library(readr)
library(class)
library(RColorBrewer)
library(FNN)
library(cluster)
library(survival)
library(survminer)
library(ggpubr)
library(dplyr)
library(httr)
```


```{r}
Breast_cancer <- read.delim("brca_tcga_clinical_data.tsv")
head(Breast_cancer)
```

brca_tcga_clinical_data.tsv
```{r}
bc_data<- read.csv("Breast_cancer_staging_V2.csv")
head(bc_data)
```
scaled_x_rna_seq2.csv
```{r}
scaled_data <- read.csv("scaled_x_rna_seq2.csv")
dim(scaled_data)
head(scaled_data)
```


```{r}
head(bc_data$breast_carcinoma_progesterone_receptor_status.x)
  
subtype_df <- subset(bc_data, select =
                       c(bcr_patient_barcode,subtype_BRCA_Subtype_PAM50,breast_carcinoma_estrogen_receptor_status.x,
                         breast_carcinoma_progesterone_receptor_status.x,lab_proc_her2_neu_immunohistochemistry_receptor_status.x))

colnames(subtype_df) <- c("id", "subtype", "estrogen_receptor","progesterone_receptor","her2_receptor")
head(subtype_df)

# Remove rows with NA values from the RNA-seq data
subtype_df <- na.omit(subtype_df)
dim(subtype_df)

subtype_smaller_df<-subset(subtype_df, subtype_df$her2_receptor != "Equivocal")   # Apply subset function
dim(subtype_smaller_df)
```

```{r}
subtype_data <- subset(subtype_df, select = c(id,subtype))
head(subtype_data)

her2_data <- subset(subtype_df, select = c(id,her2_receptor))
head(her2_data)

progesterone_data <- subset(subtype_df, select = c(id,progesterone_receptor))
head(progesterone_data)

estrogen_data <- subset(subtype_df, select = c(id,estrogen_receptor))
head(estrogen_data)

scaled_data<-na.omit(scaled_data)
     
RNAseq_data_subtype <- merge(scaled_data, subtype_data, by.x = "X", by.y = "id")
RNAseq_data_her2 <- merge(scaled_data, her2_data, by.x = "X", by.y = "id")
RNAseq_data_progesterone <- merge(scaled_data, progesterone_data, by.x = "X", by.y = "id")
RNAseq_data_estrogen <- merge(scaled_data, estrogen_data, by.x = "X", by.y = "id")

filtered_data<-merge(scaled_data,subtype_smaller_df, by.x = "X", by.y = "id")
```

##pca 
This analysis can be insightful in understanding the variation in the RNA-seq data and how it relates to the different receptor subtypes.

```{r}
pca <- prcomp(subset(RNAseq_data_estrogen, select = -c(X, estrogen_receptor)))
```

```{r}
fviz_pca_ind(pca, col.ind="cos2", geom = "point") +
      scale_color_gradient2(low="white", mid="red",high="blue", midpoint=0.2)+ theme_minimal()
```

```{r}
# Control the transparency of the color by the contributions
fviz_pca_ind(pca, col.ind="contrib") +
      scale_color_gradient2(low="lightblue", mid="blue",
      high="red", midpoint=1)
```

```{r,warning=FALSE}
p <- fviz_pca_ind(pca, label="none", habillage=RNAseq_data_subtype$subtype,
             addEllipses=TRUE, ellipse.level=0.95)
print(p)
```

```{r}
p <- fviz_pca_ind(pca, label="none", habillage=RNAseq_data_her2$her2_receptor,
             addEllipses=TRUE, ellipse.level=0.95)
print(p)
```

```{r}
p <- fviz_pca_ind(pca, label="none", habillage=RNAseq_data_estrogen$estrogen_receptor,
             addEllipses=TRUE, ellipse.level=0.95)
print(p)
```

```{r}
p <- fviz_pca_ind(pca, label="none", habillage=RNAseq_data_progesterone$progesterone_receptor,
             addEllipses=TRUE, ellipse.level=0.95)
print(p)
```


```{r}
pca_to_show <- data.frame(
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  classification = as.factor(RNAseq_data_estrogen$estrogen_receptor)
)

ggplot(pca_to_show, aes(x = PC1, y = PC2, col = classification)) +
  geom_point()

pca_to_show <- data.frame(
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  classification = as.factor(RNAseq_data_her2$her2_receptor)
)

ggplot(pca_to_show, aes(x = PC1, y = PC2, col = classification)) +
  geom_point()

pca_to_show <- data.frame(
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  classification = as.factor(RNAseq_data_progesterone$progesterone_receptor)
)

ggplot(pca_to_show, aes(x = PC1, y = PC2, col = classification)) +
  geom_point()


pca_to_show <- data.frame(
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  classification = as.factor(RNAseq_data_subtype$subtype)
)

ggplot(pca_to_show, aes(x = PC1, y = PC2, col = classification)) +
  geom_point()

```

```{r}
data<-merge(scaled_data, subtype_df, by.x = "X", by.y = "id")
numeric_data<-(subset(data, select = -c(X, subtype,estrogen_receptor,progesterone_receptor,her2_receptor)))
head(numeric_data)
```


```{r}
dim(pca$x)

pca_data <- data.frame(pca$x, RNAseq_data_subtype$subtype)

head(pca_data)
```

```{r}
set.seed(123)  # For reproducibility
train_indices <- sample(nrow(pca$x), 0.7 * nrow(pca$x))

train_data <- data.frame(pca$x[train_indices, ])
test_data <- data.frame(pca$x[-train_indices, ])

train_labels_subtype <- as.factor(pca_data$V1[train_indices])
test_labels_subtype <- pca_data$V1[-train_indices]
```

```{r}
dt_model <- rpart(train_labels_subtype ~ ., data = train_data)
predicted_labels <- predict(dt_model, test_data, type = "class")
```

```{r}
all_labels <- unique(c(train_labels_subtype, test_labels_subtype))
train_labels_subtype <- factor(train_labels_subtype, levels = all_labels)
test_labels_subtype <- factor(test_labels_subtype, levels = all_labels)
predicted_labels <- factor(predicted_labels, levels = all_labels)

# Create a confusion matrix
confusion_matrix <- confusionMatrix(predicted_labels, test_labels_subtype)

# Get accuracy from the confusion matrix
confusion_matrix
accuracy <- confusion_matrix$overall["Accuracy"]
print(accuracy)
```
#svm

```{r}
set.seed(123)

data_indices <- seq_len(nrow(numeric_data))

# Sample 70% of the row indices for the training set
train_indices <- sample(data_indices, size = 0.7 * nrow(numeric_data))

# Create the training set using the sampled row indices
train_data <- numeric_data[train_indices, ]

# Create the testing set by excluding the training set row indices
test_data <- numeric_data[-train_indices, ]

train_labels_er <- as.factor(data$estrogen_receptor[train_indices])
test_labels_er <- data$estrogen_receptor[-train_indices]

train_labels_pr <- as.factor(data$progesterone_receptor[train_indices])
test_labels_pr <- data$progesterone_receptor[-train_indices]

train_labels_her2 <- as.factor(data$her2_receptor[train_indices])
test_labels_her2 <- data$her2_receptor[-train_indices]

train_labels_subtype <- as.factor(data$subtype[train_indices])
test_labels_subtype <- data$subtype[-train_indices]
```

```{r}
# Install and load the required package
library(e1071)

# SVM function with radial basis kernel (you can try other kernels as well)
svm_model_er <- svm(x = train_data, y = train_labels_er, kernel = "radial")
svm_model_pr <- svm(x = train_data, y = train_labels_pr, kernel = "radial")
svm_model_her2 <- svm(x = train_data, y = train_labels_her2, kernel = "radial")
svm_model_subtype <- svm(x = train_data, y = train_labels_subtype, kernel = "radial")

# Make predictions on the testing set
predictions_er <- predict(svm_model_er, newdata = test_data)
predictions_pr <- predict(svm_model_pr, newdata = test_data)
predictions_her2 <- predict(svm_model_her2, newdata = test_data)
predictions_subtype <- predict(svm_model_subtype, newdata = test_data)

# Evaluate the model for each classification task (you can use accuracy, confusion matrix, etc.)
accuracy_er <- mean(predictions_er == test_labels_er)
accuracy_pr <- mean(predictions_pr == test_labels_pr)
accuracy_her2 <- mean(predictions_her2 == test_labels_her2)
accuracy_subtype <- mean(predictions_subtype == test_labels_subtype)

# Print the accuracies
print(paste("Accuracy for Estrogen Receptor:", accuracy_er))
print(paste("Accuracy for Progesterone Receptor:", accuracy_pr))
print(paste("Accuracy for HER2 Receptor:", accuracy_her2))
print(paste("Accuracy for Subtype:", accuracy_subtype))

```


#decision tree
```{r}
# Set the memory limit to 8 GB (8000 MB)
memory.limit(size = 8000)


```

```{r, warning=FALSE, out.width="70%", out.height="70%", fig.align='center'}
set.seed(0)
subtype = data$subtype
cart <- rpart(subtype ~ .,
              data = numeric_data, method = "class",
              control=rpart.control(minsplit=100,
                                    maxdepth=10,
                                    cp=0.001))
p <- predict(cart, type="class")
```

```{r, warning=FALSE, echo=FALSE, out.width="70%", out.height="70%", fig.align='center'}
print(paste0('accuracy: ',sum(p == subtype)/length(subtype)*100))

CrossTable(subtype, p, prop.chisq = FALSE, prop.c = FALSE, 
           prop.r = FALSE, dnn = c('actual type', 'predicted type'))
rpart.plot(cart)

```

```{r}
# Decision tree for Estrogen Receptor
tree_er <- rpart(factor(train_labels_er) ~ ., data = train_data, method = "class")

# Decision tree for Progesterone Receptor
tree_pr <- rpart(factor(train_labels_pr) ~ ., data = train_data, method = "class")

# Decision tree for HER2 Receptor
tree_her2 <- rpart(factor(train_labels_her2) ~ ., data = train_data, method = "class")

# Decision tree for Subtype
tree_subtype <- rpart(factor(train_labels_subtype) ~ ., data = train_data, method = "class")

# Make predictions on the testing set
predictions_er <- predict(tree_er, newdata = test_data, type = "class")
predictions_pr <- predict(tree_pr, newdata = test_data, type = "class")
predictions_her2 <- predict(tree_her2, newdata = test_data, type = "class")
predictions_subtype <- predict(tree_subtype, newdata = test_data, type = "class")

# Evaluate the model for each classification task (you can use accuracy, confusion matrix, etc.)
accuracy_er <- mean(predictions_er == test_labels_er)
accuracy_pr <- mean(predictions_pr == test_labels_pr)
accuracy_her2 <- mean(predictions_her2 == test_labels_her2)
accuracy_subtype <- mean(predictions_subtype == test_labels_subtype)

# Print the accuracies
print(paste("Accuracy for Estrogen Receptor:", accuracy_er))
print(paste("Accuracy for Progesterone Receptor:", accuracy_pr))
print(paste("Accuracy for HER2 Receptor:", accuracy_her2))
print(paste("Accuracy for Subtype:", accuracy_subtype))

```


#randomForest
```{r}
num_trees <- 100

# Random Forest for Estrogen Receptor
rf_er <- randomForest(factor(train_labels_er) ~ ., data = train_data, ntree = num_trees)

# Random Forest for Progesterone Receptor
rf_pr <- randomForest(factor(train_labels_pr) ~ ., data = train_data, ntree = num_trees)

# Random Forest for HER2 Receptor
rf_her2 <- randomForest(factor(train_labels_her2) ~ ., data = train_data, ntree = num_trees)

# Random Forest for Subtype
rf_subtype <- randomForest(factor(train_labels_subtype) ~ ., data = train_data, ntree = num_trees)

# Make predictions on the testing set
predictions_er <- predict(rf_er, newdata = test_data)
predictions_pr <- predict(rf_pr, newdata = test_data)
predictions_her2 <- predict(rf_her2, newdata = test_data)
predictions_subtype <- predict(rf_subtype, newdata = test_data)

# Evaluate the model for each classification task (you can use accuracy, confusion matrix, etc.)
accuracy_er <- mean(predictions_er == test_labels_er)
accuracy_pr <- mean(predictions_pr == test_labels_pr)
accuracy_her2 <- mean(predictions_her2 == test_labels_her2)
accuracy_subtype <- mean(predictions_subtype == test_labels_subtype)

# Print the accuracies
print(paste("Accuracy for Estrogen Receptor:", accuracy_er))
print(paste("Accuracy for Progesterone Receptor:", accuracy_pr))
print(paste("Accuracy for HER2 Receptor:", accuracy_her2))
print(paste("Accuracy for Subtype:", accuracy_subtype))

```









