---
title: "final_project"
author: "Shira, Moria, Naama"
date: "2023-06-21"
output: pdf_document
---

```{r setup, include=FALSE}
library(googledrive)
drive_auth()
```

```{r}
#y_mutation="https://drive.google.com/file/d/1q8JVD3bzpQuqT0E4xuGCKYmFoeV9E06p/view?usp=sharing"
#rna_seq="https://drive.google.com/file/d/12vP1vSCxTXweYs1AiTKoPPohmK1nRaMU/view?usp=sharing"

url="https://drive.google.com/file/d/1Ecqg0itgMpaVxuy3lbQt_OHQm77JQpif/view?usp=sharing"
drive_download(url,overwrite=TRUE)
```
```{r}
Breast_cancer <- read.delim("brca_tcga_clinical_data.tsv")
```

```{r}
Breast_cancer$ER.Status.By.IHC
```

```{r}
Breast_cancer$HER2.ihc.score
```

```{r}
Breast_cancer$ER.Status.By.IHC
```

```{r}
Breast_cancer$Overall.Survival.Status
Breast_cancer$Overall.Survival..Months.
```

```{r}

```

```{r}
#Breast_cancer$Neoplasm.American....
Breast_cancer$Patient.Primary.Tumor.Site
Breast_cancer$Patient.Metastatic.Sites
Breast_cancer$Cancer.Type.Detailed
Breast_cancer$Prior.Cancer.Diagnosis.Occurence
Breast_cancer$Surgical.procedure.first
Breast_cancer$Disease.Surgical.Margin.Status
Breast_cancer$Menopause.Status

Breast_cancer$Sex
Breast_cancer$Race.Category
```

```{r, warning=FALSE}
library(RColorBrewer)
race_counts <- table(Breast_cancer$Race.Category)
myPalette <- brewer.pal(length(race_counts), "Set2") 
pie(race_counts , labels = c("NATIVE","ASIAN","AFRICAN AMERICAN", "CAUCASIAN"), border="white", col=myPalette )

sex_counts <- table(Breast_cancer$Sex)
myPalette <- brewer.pal(length(sex_counts), "Set3") 
pie(sex_counts , labels = names(sex_counts), border="white", col=myPalette )

survival_counts <- table(Breast_cancer$Overall.Survival.Status)
myPalette <- brewer.pal(length(survival_counts), "Set2") 
pie(survival_counts , labels = c("ALIVE","DEAD"), border="white", col=myPalette )

Menopause <- table(Breast_cancer$Menopause.Status)
myPalette <- brewer.pal(length(Menopause), "Set3") 
pie(Menopause , labels = c("Indeterminate","Peri: 6-12 mos","Post : >12 mos","Pre"), border="white", col=myPalette )

```
