---
title: "RNAseq"
author: "Shira, Moria, Naama"
date: "2023-06-22"
output: html_document
---



```{r setup, include=FALSE}
library(googledrive)
library(ggplot2)
library(readr)
library(RColorBrewer)
library(httr)
```
if its the first time runing the code on your devise:
drive_auth()
clinical data
url="https://drive.google.com/file/d/1sIeLwzRQvszjkUNsefTtVdhS74Y09zbz/view?usp=sharing"
drive_download(url,overwrite=TRUE)
Rna seq
url="https://drive.google.com/file/d/1Ecqg0itgMpaVxuy3lbQt_OHQm77JQpif/view?usp=sharing"
drive_download(url,overwrite=TRUE)
mutations
url="https://drive.google.com/file/d/1165vt_jwnRiXLBHmGyC1XAobGGSPQXRt/view?usp=sharing"
drive_download(url,overwrite=TRUE)
url="https://drive.google.com/file/d/1_98OI7FKtb_Ky3lHyh0QwYPt43xYZkF2/view?usp=sharing"
drive_download(url,overwrite=TRUE)
rna_seq_data_x<-read.csv(drive_download(url,overwrite=TRUE))


```{r}
# Specify the path to your CSV file
#Breast_cancer_staging_V2
#bc_data <- read.csv("Breast_cancer_staging_V2.csv")
#head(bc_data$ihc)

bc_data <- read.delim("brca_tcga_clinical_data.tsv")
head(bc_data)
```


```{r}
data <- read.csv("scaled_x_rna_seq2.csv")
dim(data)
head(data)
```

```{r}
y_mutations <- read.csv("y_mutations2.csv")
dim(y_mutations)
head(y_mutations)
```

```{r}
# Selecting specific columns using subset()
bc_data_df <- subset(bc_data, select = c(Patient.ID,ER.Status.By.IHC,IHC.HER2,PR.status.by.ihc,Overall.Survival.Status))
head(bc_data_df)
```

```{r}
mutation_data <- merge(y_mutations, bc_data_df, by.x = "X", by.y = "Patient.ID")
head(mutation_data)
data_x_y<-merge(mutation_data, data, by.x = "X", by.y = "X")
```

## PCA on y_mutation data and scaled rna seq
```{r}
head(data_x_y)
data_x_y_pca <- data_x_y[, !(names(data_x_y) %in% c("X", "Overall.Survival.Status", "ER.Status.By.IHC", "IHC.HER2", "PR.status.by.ihc"))]
```

```{r}
standardized_data_XY <- scale(data_x_y_pca[, -ncol(data_x_y_pca)])
pca_result_XY <- prcomp(standardized_data_XY)
pc_scores_XY <- as.data.frame(pca_result_XY$x)
```

```{r}
pc_scores_XY$Overall.Survival.Status <- factor(mutation_data$Overall.Survival.Status)
pc_scores_XY$ER.Status.By.IHC <- factor(mutation_data$ER.Status.By.IHC)
pc_scores_XY$IHC.HER2 <- factor(mutation_data$IHC.HER2)
pc_scores_XY$PR.status.by.ihc <- factor(mutation_data$PR.status.by.ihc)
```

```{r}
ggplot(pc_scores_XY, aes(x = PC1, y = PC2, color = Overall.Survival.Status)) +
  geom_point() +
  labs(title = "PCA Plot - Overall Survival Status") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores_XY, aes(x = PC1, y = PC2, color = ER.Status.By.IHC)) +
  geom_point() +
  labs(title = "PCA Plot - ER Status By IHC") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores_XY, aes(x = PC1, y = PC2, color = IHC.HER2)) +
  geom_point() +
  labs(title = "PCA Plot - IHC HER2") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores_XY, aes(x = PC1, y = PC2, color = PR.status.by.ihc)) +
  geom_point() +
  labs(title = "PCA Plot - PR Status By IHC") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

```

```{r}
bc_data_df <- subset(bc_data, select = c(Patient.ID,Overall.Survival.Status,ER.Status.By.IHC,IHC.HER2,PR.status.by.ihc))
head(bc_data_df)
mutation_data <- merge(y_mutations, bc_data_df, by.x = "X", by.y = "Patient.ID")
head(mutation_data)
```

```{r}
pca_data_y <- mutation_data[, c(colnames(mutation_data)[2:45])]
standardized_data_y <- scale(pca_data_y[, -ncol(pca_data_y)])
pca_result_y <- prcomp(standardized_data_y)
pc_scores_y <- as.data.frame(pca_result_y$x)
```

```{r}
pc_scores_y$Overall.Survival.Status <- factor(mutation_data$Overall.Survival.Status)
pc_scores_y$ER.Status.By.IHC <- factor(mutation_data$ER.Status.By.IHC)
pc_scores_y$IHC.HER2 <- factor(mutation_data$IHC.HER2)
pc_scores_y$PR.status.by.ihc <- factor(mutation_data$PR.status.by.ihc)
```

```{r}
ggplot(pc_scores_y, aes(x = PC1, y = PC2, color = Overall.Survival.Status)) +
  geom_point() +
  labs(title = "PCA Plot - Overall Survival Status") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores_y, aes(x = PC1, y = PC2, color = ER.Status.By.IHC)) +
  geom_point() +
  labs(title = "PCA Plot - ER Status By IHC") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores_y, aes(x = PC1, y = PC2, color = IHC.HER2)) +
  geom_point() +
  labs(title = "PCA Plot - IHC HER2") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores_y, aes(x = PC1, y = PC2, color = PR.status.by.ihc)) +
  geom_point() +
  labs(title = "PCA Plot - PR Status By IHC") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

```
```{r}
gene_summaries <- colSums(y_mutations[, -1])
gene_summaries

id_summaries <- rowSums(y_mutations[, -1])
# Create the bar plot
barplot(table(id_summaries), main = "Frequency", xlab = "Number of mutation", ylab = "Count")
```

```{r}
bc_data_df <- subset(bc_data, select = c(Patient.ID,Overall.Survival.Status,ER.Status.By.IHC,IHC.HER2,PR.status.by.ihc))
head(bc_data_df)
RNAseq_merged <- merge(data, bc_data_df, by.x = "X", by.y = "Patient.ID")
head(RNAseq_merged)
```

```{r}
pca_data <- RNAseq_merged[, c(colnames(RNAseq_merged)[2:56499])]

standardized_data <- scale(pca_data[, -ncol(pca_data)])
pca_result <- prcomp(standardized_data)
pc_scores <- as.data.frame(pca_result$x)

```

```{r}
pc_scores$Overall.Survival.Status <- factor(RNAseq_merged$Overall.Survival.Status)
pc_scores$ER.Status.By.IHC <- factor(RNAseq_merged$ER.Status.By.IHC)
pc_scores$IHC.HER2 <- factor(RNAseq_merged$IHC.HER2)
pc_scores$PR.status.by.ihc <- factor(RNAseq_merged$PR.status.by.ihc)
```

```{r}

ggplot(pc_scores, aes(x = PC1, y = PC2, color = Overall.Survival.Status)) +
  geom_point() +
  labs(title = "PCA Plot - Overall Survival Status") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores, aes(x = PC1, y = PC2, color = ER.Status.By.IHC)) +
  geom_point() +
  labs(title = "PCA Plot - ER Status By IHC") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores, aes(x = PC1, y = PC2, color = IHC.HER2)) +
  geom_point() +
  labs(title = "PCA Plot - IHC HER2") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

ggplot(pc_scores, aes(x = PC1, y = PC2, color = PR.status.by.ihc)) +
  geom_point() +
  labs(title = "PCA Plot - PR Status By IHC") +
  xlab("PC1") +
  ylab("PC2") +
  theme_minimal()

```



